<?php
//TODO NACE AQUI
//CONFIGURAR EL .HTACCESS
require_once "configs/config.php";

//CARGAR TODO DE LA CARPETA (LBS = "libraries") PARA CAMBIAR EL LBS IR A LA CARPETA "configs" ALLI ESTA EL DOCUMENTO CON VARIABLES QUE SE USARAN
spl_autoload_register(function ($class) {
	if (file_exists(LBS . $class . ".php")) {
		require LBS . $class . ".php";
		// REQUERIMOS TODOS ARCHIVOS QUE SE ENCUENTRAN EN LA CARPETA (PUEDE QUE HAYA ERROR POR LA PRIMERA LETRA EN MAYUSCULA CUANDO SE SUBA A UN SERVIDOR, TODAVIA NO LO PRUEBO)
	}
});

// COMO YA ESTA REQUERIDO SOLO LA INSTANCIAMOS A LA CLASE APP, IR AL ARCHIVO PARA SABER MAS DE ALLI LLAMA A LAS DEMAS... 
$app = new App();